CREATE TABLE quotes (
id INTEGER PRIMARY KEY,
quote TEXT NOT NULL,
likes INTEGER DEFAULT 0,
said_by VARCHAR(255) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE quotes ADD COLUMN movie_id INTEGER DEFAULT 0 REFERENCES movies(id);